#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ      = exeflat
TRGT      = $(PROJ).exe
DESC      = DOS command interpreter
srcfiles = $(p)exeflat$(e)

ADD_COPT = -I=$(MYDIR)..$(SEP)hdr -DBUILD_UTILS

!include $(%ROOT)tools/mk/tools.mk

